// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NepHubAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NepHubAPI.Migrations
{
    [DbContext(typeof(NepHubContext))]
    [Migration("20250131191348_seedingdata")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NepHubAPI.Models.Richest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NetWorth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Richest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Chairman of Chaudhary Group",
                            Image = "https://sgp1.digitaloceanspaces.com/awe/publication-nepalaya/persons/binod_chaudhary.jpg",
                            Name = "Binod Chaudhary",
                            NetWorth = "1.4 Billion USD"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "CEO of Melbourne Institute of Technology",
                            Image = "https://republicaimg.nagariknewscdn.com/shared/web/uploads/media/shesh-ghale.jpg",
                            Name = "Shesh Ghale",
                            NetWorth = "1.2 Billion USD"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Co-founder of Melbourne Institute of Technology",
                            Image = "https://biographnepal.com/wp-content/uploads/2024/09/Jamuna-Gurung-e1727365992412.jpg",
                            Name = "Jamuna Gurung",
                            NetWorth = "1.2 Billion USD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
